import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  // database.types.ts is generated by the Supabase CLI. Linting it means either fighting the
  // generator or hand-editing a file that gets overwritten on the next migration.
  {
    ignores: [
      'dist',
      'node_modules',
      'src/backend/database.types.ts',
      // Root-level scratch drivers (see .gitignore). Throwaway by definition, and a lint error in
      // one of them should never be able to fail the project's lint.
      '.drive*.mjs',
      '.probe.mjs',
      '.play.mjs',
      '.beat.mjs',
    ],
  },
  js.configs.recommended,
  tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // The sim runs hot; prefer explicit numbers over clever coercion.
      eqeqeq: ['error', 'always'],
      'no-console': 'off',
    },
  },
  {
    files: ['vite.config.ts'],
    languageOptions: { globals: globals.node },
  },
  {
    // Config files and the Node-side scripts are plain JS and live outside the TS projects, so
    // the type-aware rules have no program to consult and would error on the file itself.
    files: ['**/*.js', '**/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: { globals: globals.node },
  },
  prettier,
);
